### PR TITLE
Some additions I found useful

### PR DESCRIPTION
**Pull request by upegelow**
- mirror machine status on serial output
- indicate if machine is in "fast heating" mode
- reset timer count to zero when going to sleep

### CODE REVIEW

**Comment by EssayAssay** [comment]
@upegelow Thanks for the suggestions, will test them in the next few days and I'll let you know.

Until then, do you have any info about the fast heating mode? when and how it's suppose to work? I wanted to make some changes to the code so that when the counter reaches "0000" it should send a notification to my phone that machine is ready, but something is not working correctly, I'm getting a notification every minute or so, randomly, not sure if code is wrong, or the counter changes from "0000" to some other value and then back to "0000"

**Comment by alexrus** [comment]
@upegelow Thanks for the suggestions, will test them in the next few days and I'll let you know.

Until then, do you have any info about the fast heating mode? when and how it's suppose to work? I wanted to make some changes to the code so that when the counter reaches "0000" it should send a notification to my phone that machine is ready, but something is not working correctly, I'm getting a notification every minute or so, randomly, not sure if code is wrong, or the counter changes from "0000" to some other value and then back to "0000"

**Comment by upegelow** [comment]
Frankly, I also still try to find out what it really does. That mode seems to be always active at the beginning of the heat-up phase of the machine. Not sure if there are cases where it gets activated later on. Finding out about this was my primary idea for the change. Observations so far: in this mode it will start counting down from 1200 constantly but often then drop to 0000 from some intermediate count value.

**Comment by alexrus** [comment]
@upegelow I'll merge your changes in, they look good.

I did some investigations, and yes, the counter starts at 1200 and stopped at 0222, that's also the time where the boilter set temp (not real temp) changed from 140C to 128C . Some more time passed, and then it changed from 128 to 135. at this point, the ready light turned on on the machine.

**Comment by upegelow** [comment]
Cool, thanks! And I forgot to thank you @alexrus for this marvelous little project. It's exactly what I was looking for and proves as a really valuable extension using the potential of the machine to its full extent.

I investigated a bit further:

- Fast heating mode seems to get activated in two situations: either the machine has just been started, or it has been revoked from energy saving mode. Characteristically, In both cases initial boiler set-temperature is zero just before fast heating mode starts

- The countdown starts at 1200 seconds. In most cases it will terminate before reaching zero. I could not find out what the exact condition is for termination. Best guess so far: when the HX temperature has reached 90°C for some seconds (may depend on mode setting, in my case coffee priority and temperature I).

- Fast heating mode does not imply that the heating is on all the time. Also in this mode we see on/off changes. Speculation: maybe the temperature regulation is less damped in favor of a fast heating at the costs of some temperature overshoot.

**Pull request merged**
